#index:
#    path: /
#    controller: App\Controller\DefaultController::index

especialidades:
  path: /especialidades
  controller: App\Controller\EspecialidadesController::index
  methods:
    - GET

especialidade:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadesController::show
  methods:
    - GET

medicos:
  path: /medicos
  controller: App\Controller\MedicosController::index
  methods:
    - GET

medico:
  path: /medicos/{id}
  controller: App\Controller\MedicosController::show
  methods:
    - GET