#index:
#    path: /
#    controller: App\Controller\DefaultController::index

especialidades:
  path: /especialidades
  controller: App\Controller\EspecialidadesController::index
  methods:
    - GET

medicos:
  path: /medicos
  controller: App\Controller\MedicosController::index
  methods:
    - GET