#index:
#    path: /
#    controller: App\Controller\DefaultController::index

especialidades:
  path: /especialidades
  controller: App\Controller\EspecialidadesController::index
  methods:
    - GET

especialidade:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadesController::show
  methods:
    - GET

remove_especialidade:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadesController::destroy
  methods:
    - DELETE

cria_especialidade:
  path: /especialidades
  controller: App\Controller\EspecialidadesController::store
  methods:
    - POST

atualiza_especialidade:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadesController::update
  methods:
    - PUT

medicos:
  path: /medicos
  controller: App\Controller\MedicosController::index
  methods:
    - GET

medico:
  path: /medicos/{id}
  controller: App\Controller\MedicosController::show
  methods:
    - GET

remove_medico:
  path: /medicos/{id}
  controller: App\Controller\MedicosController::destroy
  methods:
    - GET

cria_medico:
  path: /medicos
  controller: App\Controller\MedicosController::store
  methods:
    - POST

atualiza_medico:
  path: /medicos/{id}
  controller: App\Controller\MedicosController::update
  methods:
    - PUT